### ISSUE TITLE
Drop Python 2.6 skip

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/zeep-feedstock#7]
There is a Python 2.6 skip in the recipe. However Python 2.6 is not being built or supported in conda-forge. So this can safely be dropped from the recipe.

https://github.com/conda-forge/zeep-feedstock/blob/70136f24d43698c91882e0018f95c26a11a909b8/recipe/meta.yaml#L17

**Comment by hugovk** [comment]
Please see PR #10.

**Comment by hugovk** [comment]
It has been removed. This issue can be closed.

**Comment by jakirkham** [comment]
Thanks @hugovk :)
